// 各デモ画面のトンマナ定義。Tailwind クラスをそのまま埋め込む方式で
// 動的クラス名生成（v4のパージ対象外）を避ける。

export type ThemeId =
  | "italian"
  | "izakaya"
  | "cafe"
  | "yakiniku"
  | "sushi"
  | "ramen"
  | "salon"
  | "nail"
  | "bakery"
  | "teishoku"
  | "wagashi"
  | "soba"
  | "kaiseki"
  | "teppanyaki"
  | "french"
  | "chinese"
  | "taishu"
  | "okonomiyaki"
  | "udon"
  | "wine-bar"
  | "craft-beer"
  | "cocktail-bar"
  | "patisserie"
  | "gelato"
  | "burger"
  | "modern-cafe"
  | "teahouse"
  | "eyelash"
  | "barber"
  | "family";

export type LayoutVariant = "card" | "list" | "grid-tight" | "rail";

export type Theme = {
  id: ThemeId;
  // ページ全体
  pageBg: string;
  pageText: string;
  // ヘッダー
  headerBg: string;
  headerText: string;
  headerAccent: string; // 飾り罫線・小見出し用
  // カテゴリ見出し
  catHeading: string; // h2
  catSub: string;
  catRule: string; // 罫線色（border-...）
  // 商品カード
  cardWrap: string; // 1商品分の枠
  cardName: string;
  cardSub: string;
  cardDesc: string;
  cardPrice: string;
  cardBadge: string;
  cardImagePh: string; // 画像未挿入のプレースホルダー
  // セクション間隔・グリッド
  sectionGap: string;
  grid: string;
  // フッター注記
  footerNote: string;
  // 全体フォント（layout で適用）
  fontFamily: string; // serif/sans 切替
  layout: LayoutVariant;
  // 背景画像オーバーレイ・モード（任意）
  bgImage?: string; // フルブリードの背景画像URL
  bgOverlay?: string; // CSSグラデーション。デフォルトは暗めの黒オーバーレイ
};

export const THEMES: Record<ThemeId, Theme> = {
  italian: {
    id: "italian",
    pageBg: "bg-black",
    pageText: "text-stone-50",
    headerBg: "bg-transparent",
    headerText: "text-stone-50",
    headerAccent: "text-amber-200",
    catHeading: "font-serif text-3xl tracking-wider text-stone-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.4em] text-amber-200 uppercase",
    catRule: "border-amber-200/40",
    cardWrap:
      "flex gap-3 rounded-md border border-white/15 bg-black/45 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-stone-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-200/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-sm text-amber-100 sm:text-base",
    cardBadge:
      "rounded-full border border-amber-200/60 px-2 py-0.5 text-[10px] tracking-wider text-amber-100",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/50",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-4 sm:grid-cols-2 sm:gap-5",
    footerNote: "text-stone-400",
    fontFamily: "font-serif",
    layout: "card",
    bgImage:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=2000&q=80",
    bgOverlay:
      "linear-gradient(rgba(15,12,8,0.72), rgba(15,12,8,0.85))",
  },
  izakaya: {
    id: "izakaya",
    pageBg: "bg-black",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-stone-100",
    headerAccent: "text-red-300",
    bgImage:
      "https://images.unsplash.com/photo-1554502078-ef0fc409efce?w=2000&q=80",
    bgOverlay:
      "linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.85))",
    catHeading:
      "font-serif text-2xl tracking-widest text-stone-100 sm:text-3xl",
    catSub: "text-[11px] tracking-[0.4em] text-red-400/80",
    catRule: "border-stone-700",
    cardWrap:
      "flex gap-3 border-b border-white/15 bg-transparent px-1 py-3 sm:gap-4 sm:py-4",
    cardName: "text-sm text-stone-100 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-stone-400 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-400 sm:text-xs",
    cardPrice: "font-serif text-sm text-red-300 sm:text-base",
    cardBadge:
      "border border-red-400/60 px-2 py-0.5 text-[10px] tracking-wider text-red-300",
    cardImagePh: "bg-stone-800 text-[10px] tracking-[0.2em] text-stone-600",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-8",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "list",
  },
  cafe: {
    id: "cafe",
    pageBg: "bg-[#faf6ef]",
    pageText: "text-stone-800",
    headerBg: "bg-[#faf6ef]",
    headerText: "text-stone-800",
    headerAccent: "text-amber-800/70",
    catHeading:
      "font-serif text-xl italic text-stone-800 sm:text-2xl",
    catSub: "text-[10px] tracking-[0.3em] text-amber-800/70 uppercase",
    catRule: "border-stone-300",
    cardWrap:
      "flex gap-3 rounded-2xl border border-stone-200 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-800/70 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-500 sm:text-xs",
    cardPrice: "font-serif italic text-sm text-stone-900 sm:text-base",
    cardBadge:
      "rounded-full bg-amber-50 px-2 py-0.5 text-[10px] tracking-wider text-amber-800",
    cardImagePh: "bg-stone-100 text-[10px] tracking-[0.2em] text-stone-400",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "card",
  },
  yakiniku: {
    id: "yakiniku",
    pageBg: "bg-black",
    pageText: "text-amber-50",
    headerBg: "bg-transparent",
    headerText: "text-amber-50",
    headerAccent: "text-amber-300",
    bgImage:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=2000&q=80",
    bgOverlay:
      "linear-gradient(rgba(8,4,2,0.7), rgba(20,8,4,0.88))",
    catHeading:
      "text-2xl font-bold tracking-wider text-amber-50 sm:text-3xl",
    catSub: "text-[11px] tracking-[0.4em] text-amber-400 uppercase",
    catRule: "border-amber-900/40",
    cardWrap:
      "flex gap-3 rounded border border-amber-200/25 bg-black/50 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "text-sm font-semibold text-amber-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-200/70 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-400 sm:text-xs",
    cardPrice: "text-sm font-bold text-amber-300 sm:text-base",
    cardBadge:
      "rounded-sm bg-red-700 px-2 py-0.5 text-[10px] font-medium tracking-wider text-amber-50",
    cardImagePh: "bg-stone-800 text-[10px] tracking-[0.2em] text-stone-600",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  sushi: {
    id: "sushi",
    pageBg: "bg-black",
    pageText: "text-slate-100",
    headerBg: "bg-transparent",
    headerText: "text-slate-50",
    headerAccent: "text-slate-300",
    bgImage: "https://picsum.photos/seed/sushi-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(10,15,25,0.78), rgba(5,10,20,0.92))",
    catHeading: "font-serif text-3xl tracking-[0.3em] text-slate-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.5em] text-slate-300 uppercase",
    catRule: "border-slate-300/40",
    cardWrap:
      "flex items-baseline justify-between gap-3 border-b border-dotted border-slate-300/30 px-1 py-3 sm:gap-6 sm:py-4",
    cardName: "font-serif text-sm text-slate-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-slate-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-slate-300 sm:text-xs",
    cardPrice: "font-serif text-sm tabular-nums text-slate-100 sm:text-base",
    cardBadge:
      "border border-slate-300 px-2 py-0.5 text-[10px] tracking-wider text-slate-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-10",
    footerNote: "text-slate-400",
    fontFamily: "font-serif",
    layout: "list",
  },
  ramen: {
    id: "ramen",
    pageBg: "bg-black",
    pageText: "text-amber-50",
    headerBg: "bg-transparent",
    headerText: "text-amber-50",
    headerAccent: "text-red-400",
    bgImage: "https://picsum.photos/seed/ramen-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(20,8,5,0.72), rgba(10,4,2,0.9))",
    catHeading: "text-3xl font-extrabold tracking-wider text-amber-50 sm:text-4xl",
    catSub: "text-[11px] font-bold tracking-[0.3em] text-red-400",
    catRule: "border-red-400/40",
    cardWrap:
      "flex gap-3 rounded border-2 border-amber-200/30 bg-black/45 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "text-base font-bold text-amber-50 sm:text-lg",
    cardSub: "text-[10px] tracking-wider text-red-300 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice:
      "text-base font-extrabold tabular-nums text-red-300 sm:text-lg",
    cardBadge:
      "rounded-sm bg-amber-300 px-2 py-0.5 text-[10px] font-bold tracking-wider text-stone-900",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-10 sm:space-y-12",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-400",
    fontFamily: "font-sans",
    layout: "card",
  },
  salon: {
    id: "salon",
    pageBg: "bg-white",
    pageText: "text-neutral-900",
    headerBg: "bg-white",
    headerText: "text-neutral-900",
    headerAccent: "text-neutral-500",
    catHeading:
      "font-serif text-xl font-light tracking-wider text-neutral-900 sm:text-2xl",
    catSub: "text-[10px] tracking-[0.4em] text-neutral-500 uppercase",
    catRule: "border-neutral-200",
    cardWrap: "flex gap-4 bg-white p-4 sm:gap-5 sm:p-5",
    cardName: "font-serif text-sm font-normal tracking-wide text-neutral-900 sm:text-base",
    cardSub: "text-[10px] tracking-[0.25em] text-neutral-500 uppercase",
    cardDesc: "text-[11px] leading-relaxed text-neutral-600 sm:text-xs",
    cardPrice: "text-sm font-light tracking-wider text-neutral-900 sm:text-base",
    cardBadge:
      "border border-neutral-900 px-2 py-0.5 text-[10px] tracking-widest text-neutral-900",
    cardImagePh: "bg-neutral-100 text-[10px] tracking-[0.25em] text-neutral-400",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-px border border-neutral-200 bg-neutral-200 sm:grid-cols-2",
    footerNote: "text-neutral-500",
    fontFamily: "font-serif",
    layout: "grid-tight",
  },
  nail: {
    id: "nail",
    pageBg: "bg-[#fdf4f3]",
    pageText: "text-stone-800",
    headerBg: "bg-[#fdf4f3]",
    headerText: "text-stone-800",
    headerAccent: "text-rose-400",
    catHeading:
      "font-serif text-xl text-stone-800 sm:text-2xl",
    catSub: "text-[10px] tracking-[0.4em] text-rose-400 uppercase",
    catRule: "border-rose-200",
    cardWrap:
      "flex gap-3 rounded-2xl border border-rose-100 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-[0.25em] text-rose-400 uppercase",
    cardDesc: "text-[11px] leading-relaxed text-stone-500 sm:text-xs",
    cardPrice: "font-serif text-sm text-stone-900 sm:text-base",
    cardBadge:
      "rounded-full bg-rose-100 px-2 py-0.5 text-[10px] tracking-wider text-rose-600",
    cardImagePh: "bg-rose-50 text-[10px] tracking-[0.2em] text-rose-300",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "card",
  },
  teishoku: {
    id: "teishoku",
    pageBg: "bg-[#f5ede0]",
    pageText: "text-stone-800",
    headerBg: "bg-[#f5ede0]",
    headerText: "text-stone-900",
    headerAccent: "text-amber-800",
    catHeading: "font-serif text-2xl text-stone-900 sm:text-3xl",
    catSub: "text-[11px] tracking-[0.3em] text-amber-800 uppercase",
    catRule: "border-amber-800/30",
    cardWrap: "flex gap-3 rounded-md border border-amber-800/15 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-800/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-600 sm:text-xs",
    cardPrice: "font-serif text-sm text-stone-900 sm:text-base",
    cardBadge: "rounded-full bg-amber-100 px-2 py-0.5 text-[10px] tracking-wider text-amber-900",
    cardImagePh: "bg-stone-100 text-[10px] tracking-[0.2em] text-stone-400",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "card",
  },
  wagashi: {
    id: "wagashi",
    pageBg: "bg-[#fafaf6]",
    pageText: "text-stone-800",
    headerBg: "bg-[#fafaf6]",
    headerText: "text-stone-900",
    headerAccent: "text-rose-900/70",
    catHeading: "font-serif text-2xl tracking-[0.3em] text-stone-900 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.4em] text-rose-900/70 uppercase",
    catRule: "border-stone-300",
    cardWrap: "flex gap-3 border-b border-stone-300 bg-transparent px-1 py-3 sm:gap-4 sm:py-4",
    cardName: "font-serif text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-rose-900/60 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-600 sm:text-xs",
    cardPrice: "font-serif text-sm tabular-nums text-stone-900 sm:text-base",
    cardBadge: "border border-rose-900/40 px-2 py-0.5 text-[10px] tracking-wider text-rose-900/80",
    cardImagePh: "bg-stone-100 text-[10px] tracking-[0.2em] text-stone-400",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-10",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "list",
  },
  soba: {
    id: "soba",
    pageBg: "bg-[#f1ece1]",
    pageText: "text-stone-800",
    headerBg: "bg-[#f1ece1]",
    headerText: "text-stone-900",
    headerAccent: "text-stone-700",
    catHeading: "font-serif text-2xl text-stone-900 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.4em] text-stone-700 uppercase",
    catRule: "border-stone-400",
    cardWrap: "flex gap-3 border-b border-stone-400/60 bg-transparent px-1 py-3 sm:gap-4 sm:py-4",
    cardName: "font-serif text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-stone-600 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-600 sm:text-xs",
    cardPrice: "font-serif text-sm tabular-nums text-stone-900 sm:text-base",
    cardBadge: "border border-stone-600 px-2 py-0.5 text-[10px] tracking-wider text-stone-700",
    cardImagePh: "bg-stone-200 text-[10px] tracking-[0.2em] text-stone-500",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-10",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "list",
  },
  kaiseki: {
    id: "kaiseki",
    pageBg: "bg-black",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-amber-100",
    headerAccent: "text-amber-300",
    bgImage: "https://picsum.photos/seed/kaiseki-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(10,20,15,0.78), rgba(5,10,8,0.92))",
    catHeading: "font-serif text-3xl tracking-[0.3em] text-amber-100 sm:text-4xl",
    catSub: "text-[10px] tracking-[0.5em] text-amber-300 uppercase",
    catRule: "border-amber-300/40",
    cardWrap: "flex gap-3 border-b border-amber-300/20 bg-transparent px-1 py-4 sm:gap-4 sm:py-5",
    cardName: "font-serif text-base tracking-wide text-amber-50 sm:text-lg",
    cardSub: "text-[10px] tracking-[0.3em] text-amber-300/70",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-base tabular-nums text-amber-200 sm:text-lg",
    cardBadge: "border border-amber-300/60 px-2 py-0.5 text-[10px] tracking-[0.2em] text-amber-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-14 sm:space-y-20",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-12",
    footerNote: "text-amber-200/60",
    fontFamily: "font-serif",
    layout: "list",
  },
  teppanyaki: {
    id: "teppanyaki",
    pageBg: "bg-black",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-stone-100",
    headerAccent: "text-red-400",
    bgImage: "https://picsum.photos/seed/teppanyaki-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(22,18,16,0.78), rgba(8,4,2,0.92))",
    catHeading: "text-3xl font-bold tracking-wider text-stone-100 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.4em] text-red-400 uppercase",
    catRule: "border-red-500/40",
    cardWrap: "flex gap-3 rounded border border-red-500/25 bg-black/45 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "text-sm font-semibold text-stone-100 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-red-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-400 sm:text-xs",
    cardPrice: "text-sm font-bold text-red-300 sm:text-base",
    cardBadge: "rounded-sm bg-red-600 px-2 py-0.5 text-[10px] tracking-wider text-stone-100",
    cardImagePh: "bg-stone-800 text-[10px] tracking-[0.2em] text-stone-600",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  french: {
    id: "french",
    pageBg: "bg-[#0d1424]",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-amber-100",
    headerAccent: "text-amber-300",
    bgImage: "https://picsum.photos/seed/french-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(13,20,36,0.85), rgba(8,12,22,0.92))",
    catHeading: "font-serif text-3xl italic text-amber-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.4em] text-amber-300 uppercase",
    catRule: "border-amber-300/30",
    cardWrap: "flex gap-3 rounded border border-amber-300/15 bg-black/40 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm italic text-amber-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-sm text-amber-200 sm:text-base",
    cardBadge: "rounded-full border border-amber-300/60 px-2 py-0.5 text-[10px] tracking-wider text-amber-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-4 sm:grid-cols-2 sm:gap-5",
    footerNote: "text-amber-200/60",
    fontFamily: "font-serif",
    layout: "card",
  },
  chinese: {
    id: "chinese",
    pageBg: "bg-black",
    pageText: "text-amber-50",
    headerBg: "bg-transparent",
    headerText: "text-amber-50",
    headerAccent: "text-amber-400",
    bgImage: "https://picsum.photos/seed/chinese-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(26,8,8,0.82), rgba(12,4,4,0.93))",
    catHeading: "font-serif text-3xl font-bold text-amber-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.4em] text-amber-400 uppercase",
    catRule: "border-amber-500/40",
    cardWrap: "flex gap-3 rounded-sm border-2 border-amber-500/30 bg-black/50 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm font-semibold text-amber-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-200/70 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-sm font-bold text-amber-300 sm:text-base",
    cardBadge: "rounded-sm bg-amber-500 px-2 py-0.5 text-[10px] font-bold tracking-wider text-red-900",
    cardImagePh: "bg-stone-800 text-[10px] tracking-[0.2em] text-stone-600",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-amber-200/60",
    fontFamily: "font-serif",
    layout: "card",
  },
  taishu: {
    id: "taishu",
    pageBg: "bg-[#f5e6b8]",
    pageText: "text-stone-900",
    headerBg: "bg-[#f5e6b8]",
    headerText: "text-red-900",
    headerAccent: "text-red-800",
    catHeading: "text-3xl font-black tracking-wider text-red-900 sm:text-4xl",
    catSub: "text-[11px] font-bold tracking-[0.3em] text-red-800",
    catRule: "border-red-900/40",
    cardWrap: "flex gap-3 rounded border-2 border-red-900/40 bg-[#fff5cf] p-3 sm:gap-4 sm:p-4",
    cardName: "text-base font-bold text-stone-900 sm:text-lg",
    cardSub: "text-[10px] tracking-wider text-red-800 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-700 sm:text-xs",
    cardPrice: "text-lg font-black tabular-nums text-red-800 sm:text-xl",
    cardBadge: "rounded-sm bg-red-700 px-2 py-0.5 text-[10px] font-bold tracking-wider text-amber-50",
    cardImagePh: "bg-amber-100 text-[10px] tracking-[0.2em] text-amber-700",
    sectionGap: "space-y-10 sm:space-y-12",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-600",
    fontFamily: "font-sans",
    layout: "card",
  },
  okonomiyaki: {
    id: "okonomiyaki",
    pageBg: "bg-[#fffbe8]",
    pageText: "text-stone-900",
    headerBg: "bg-[#fffbe8]",
    headerText: "text-stone-900",
    headerAccent: "text-red-600",
    catHeading: "text-2xl font-extrabold text-stone-900 sm:text-3xl",
    catSub: "text-[11px] font-bold tracking-[0.3em] text-red-600",
    catRule: "border-red-600/40",
    cardWrap: "flex gap-3 rounded border-2 border-stone-900 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "text-base font-bold text-stone-900 sm:text-lg",
    cardSub: "text-[10px] tracking-wider text-red-600 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-700 sm:text-xs",
    cardPrice: "text-base font-extrabold tabular-nums text-red-600 sm:text-lg",
    cardBadge: "rounded-sm bg-yellow-400 px-2 py-0.5 text-[10px] font-bold tracking-wider text-stone-900",
    cardImagePh: "bg-stone-100 text-[10px] tracking-[0.2em] text-stone-400",
    sectionGap: "space-y-10 sm:space-y-12",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  udon: {
    id: "udon",
    pageBg: "bg-[#f5f9fc]",
    pageText: "text-slate-900",
    headerBg: "bg-[#f5f9fc]",
    headerText: "text-slate-900",
    headerAccent: "text-blue-800",
    catHeading: "font-serif text-2xl text-slate-900 sm:text-3xl",
    catSub: "text-[11px] tracking-[0.4em] text-blue-800 uppercase",
    catRule: "border-blue-800/30",
    cardWrap: "flex gap-3 border-b-2 border-blue-800/20 bg-transparent px-1 py-3 sm:gap-4 sm:py-4",
    cardName: "font-serif text-sm text-slate-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-blue-700 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-slate-600 sm:text-xs",
    cardPrice: "font-serif text-sm tabular-nums text-slate-900 sm:text-base",
    cardBadge: "border border-blue-800 px-2 py-0.5 text-[10px] tracking-wider text-blue-800",
    cardImagePh: "bg-slate-100 text-[10px] tracking-[0.2em] text-slate-400",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-10",
    footerNote: "text-slate-500",
    fontFamily: "font-serif",
    layout: "list",
  },
  "wine-bar": {
    id: "wine-bar",
    pageBg: "bg-[#1c0810]",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-rose-100",
    headerAccent: "text-rose-300",
    bgImage: "https://picsum.photos/seed/wine-bar-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(28,8,16,0.85), rgba(12,4,8,0.92))",
    catHeading: "font-serif text-3xl italic text-rose-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.4em] text-rose-300 uppercase",
    catRule: "border-rose-300/30",
    cardWrap: "flex gap-3 rounded border border-rose-300/20 bg-black/40 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm italic text-rose-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-rose-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-sm tabular-nums text-rose-200 sm:text-base",
    cardBadge: "rounded-full border border-rose-300/60 px-2 py-0.5 text-[10px] tracking-wider text-rose-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-4 sm:grid-cols-2 sm:gap-5",
    footerNote: "text-rose-200/60",
    fontFamily: "font-serif",
    layout: "card",
  },
  "craft-beer": {
    id: "craft-beer",
    pageBg: "bg-black",
    pageText: "text-amber-50",
    headerBg: "bg-transparent",
    headerText: "text-amber-50",
    headerAccent: "text-amber-400",
    bgImage: "https://picsum.photos/seed/craftbeer-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(28,18,8,0.78), rgba(12,8,4,0.92))",
    catHeading: "text-3xl font-black uppercase tracking-wider text-amber-50 sm:text-4xl",
    catSub: "text-[11px] font-bold tracking-[0.4em] text-amber-400",
    catRule: "border-amber-500/40",
    cardWrap: "flex gap-3 rounded border-2 border-amber-500/30 bg-black/50 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "text-sm font-bold uppercase tracking-wider text-amber-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-200/70 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-400 sm:text-xs",
    cardPrice: "text-sm font-black tabular-nums text-amber-300 sm:text-base",
    cardBadge: "rounded-sm bg-amber-500 px-2 py-0.5 text-[10px] font-bold tracking-wider text-stone-900",
    cardImagePh: "bg-stone-800 text-[10px] tracking-[0.2em] text-stone-600",
    sectionGap: "space-y-10 sm:space-y-12",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-amber-200/60",
    fontFamily: "font-sans",
    layout: "card",
  },
  "cocktail-bar": {
    id: "cocktail-bar",
    pageBg: "bg-[#0a0815]",
    pageText: "text-violet-100",
    headerBg: "bg-transparent",
    headerText: "text-violet-100",
    headerAccent: "text-amber-300",
    bgImage: "https://picsum.photos/seed/cocktail-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(10,8,21,0.85), rgba(5,4,12,0.92))",
    catHeading: "font-serif text-3xl tracking-widest text-violet-50 sm:text-4xl",
    catSub: "text-[11px] tracking-[0.5em] text-amber-300 uppercase",
    catRule: "border-amber-300/30",
    cardWrap: "flex gap-3 rounded border border-amber-300/15 bg-black/50 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm tracking-wide text-violet-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-violet-200/70 sm:text-xs",
    cardPrice: "font-serif text-sm text-amber-200 sm:text-base",
    cardBadge: "rounded-full border border-amber-300/60 px-2 py-0.5 text-[10px] tracking-wider text-amber-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-4 sm:grid-cols-2 sm:gap-5",
    footerNote: "text-violet-200/60",
    fontFamily: "font-serif",
    layout: "card",
  },
  patisserie: {
    id: "patisserie",
    pageBg: "bg-[#fdf2ea]",
    pageText: "text-stone-800",
    headerBg: "bg-[#fdf2ea]",
    headerText: "text-stone-900",
    headerAccent: "text-rose-500",
    catHeading: "font-serif text-2xl italic text-stone-900 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.4em] text-rose-500 uppercase",
    catRule: "border-rose-300",
    cardWrap: "flex gap-3 rounded-3xl border border-rose-200/70 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-rose-500 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-500 sm:text-xs",
    cardPrice: "font-serif italic text-sm text-stone-900 sm:text-base",
    cardBadge: "rounded-full bg-rose-100 px-2 py-0.5 text-[10px] tracking-wider text-rose-700",
    cardImagePh: "bg-rose-50 text-[10px] tracking-[0.2em] text-rose-300",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "card",
  },
  gelato: {
    id: "gelato",
    pageBg: "bg-[#fff7f5]",
    pageText: "text-stone-800",
    headerBg: "bg-[#fff7f5]",
    headerText: "text-stone-900",
    headerAccent: "text-pink-500",
    catHeading: "text-2xl font-bold text-stone-900 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.3em] text-pink-500 uppercase",
    catRule: "border-pink-300",
    cardWrap: "flex gap-3 rounded-3xl border-2 border-pink-200 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "text-sm font-semibold text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-pink-500 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-500 sm:text-xs",
    cardPrice: "text-sm font-bold text-pink-600 sm:text-base",
    cardBadge: "rounded-full bg-yellow-300 px-2 py-0.5 text-[10px] font-bold tracking-wider text-stone-900",
    cardImagePh: "bg-pink-50 text-[10px] tracking-[0.2em] text-pink-300",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  burger: {
    id: "burger",
    pageBg: "bg-[#fff7eb]",
    pageText: "text-stone-900",
    headerBg: "bg-[#fff7eb]",
    headerText: "text-red-700",
    headerAccent: "text-red-700",
    catHeading: "text-3xl font-black uppercase tracking-wider text-red-700 sm:text-4xl",
    catSub: "text-[11px] font-bold tracking-[0.3em] text-stone-700",
    catRule: "border-red-700/40",
    cardWrap: "flex gap-3 rounded border-2 border-stone-900 bg-white p-3 shadow-[4px_4px_0_rgba(0,0,0,1)] sm:gap-4 sm:p-4",
    cardName: "text-base font-black uppercase tracking-wider text-stone-900 sm:text-lg",
    cardSub: "text-[10px] tracking-wider text-red-700 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-700 sm:text-xs",
    cardPrice: "text-base font-black tabular-nums text-red-700 sm:text-lg",
    cardBadge: "rounded-sm bg-yellow-400 px-2 py-0.5 text-[10px] font-bold tracking-wider text-stone-900",
    cardImagePh: "bg-stone-100 text-[10px] tracking-[0.2em] text-stone-400",
    sectionGap: "space-y-10 sm:space-y-12",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  "modern-cafe": {
    id: "modern-cafe",
    pageBg: "bg-white",
    pageText: "text-neutral-900",
    headerBg: "bg-white",
    headerText: "text-neutral-900",
    headerAccent: "text-neutral-400",
    catHeading: "text-2xl font-light tracking-wider text-neutral-900 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.4em] text-neutral-400 uppercase",
    catRule: "border-neutral-200",
    cardWrap: "flex gap-3 border-b border-neutral-200 bg-transparent px-1 py-4 sm:gap-4 sm:py-5",
    cardName: "text-sm font-medium text-neutral-900 sm:text-base",
    cardSub: "text-[10px] tracking-[0.25em] text-neutral-400 uppercase",
    cardDesc: "text-[11px] leading-relaxed text-neutral-500 sm:text-xs",
    cardPrice: "text-sm font-light tabular-nums text-neutral-900 sm:text-base",
    cardBadge: "border border-neutral-900 px-2 py-0.5 text-[10px] tracking-widest text-neutral-900",
    cardImagePh: "bg-neutral-100 text-[10px] tracking-[0.25em] text-neutral-400",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-12",
    footerNote: "text-neutral-500",
    fontFamily: "font-sans",
    layout: "list",
  },
  teahouse: {
    id: "teahouse",
    pageBg: "bg-black",
    pageText: "text-emerald-50",
    headerBg: "bg-transparent",
    headerText: "text-emerald-50",
    headerAccent: "text-emerald-300",
    bgImage: "https://picsum.photos/seed/teahouse-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(14,26,20,0.82), rgba(6,12,8,0.92))",
    catHeading: "font-serif text-3xl tracking-[0.3em] text-emerald-50 sm:text-4xl",
    catSub: "text-[10px] tracking-[0.5em] text-emerald-300 uppercase",
    catRule: "border-emerald-300/30",
    cardWrap: "flex gap-3 rounded-md border border-emerald-300/15 bg-black/40 p-3 backdrop-blur-md sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-emerald-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-emerald-300/80 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "font-serif text-sm text-emerald-200 sm:text-base",
    cardBadge: "rounded-full border border-emerald-300/60 px-2 py-0.5 text-[10px] tracking-wider text-emerald-200",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-emerald-200/60",
    fontFamily: "font-serif",
    layout: "card",
  },
  eyelash: {
    id: "eyelash",
    pageBg: "bg-black",
    pageText: "text-stone-100",
    headerBg: "bg-transparent",
    headerText: "text-stone-100",
    headerAccent: "text-rose-300",
    bgImage: "https://picsum.photos/seed/eyelash-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(26,21,24,0.85), rgba(10,8,10,0.93))",
    catHeading: "font-serif text-3xl font-light tracking-[0.3em] text-stone-100 sm:text-4xl",
    catSub: "text-[10px] tracking-[0.4em] text-rose-300 uppercase",
    catRule: "border-rose-300/30",
    cardWrap: "flex gap-3 border-b border-rose-300/15 bg-transparent px-1 py-4 sm:gap-4 sm:py-5",
    cardName: "font-serif text-sm font-light tracking-wide text-stone-100 sm:text-base",
    cardSub: "text-[10px] tracking-[0.25em] text-rose-300/80 uppercase",
    cardDesc: "text-[11px] leading-relaxed text-stone-400 sm:text-xs",
    cardPrice: "font-serif text-sm font-light tabular-nums text-rose-200 sm:text-base",
    cardBadge: "border border-rose-300/60 px-2 py-0.5 text-[10px] tracking-widest text-rose-200",
    cardImagePh: "bg-white/5 text-[10px] tracking-[0.25em] text-white/30",
    sectionGap: "space-y-12 sm:space-y-16",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-12",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "list",
  },
  barber: {
    id: "barber",
    pageBg: "bg-black",
    pageText: "text-amber-50",
    headerBg: "bg-transparent",
    headerText: "text-amber-50",
    headerAccent: "text-red-300",
    bgImage: "https://picsum.photos/seed/barber-bg/2000/1200",
    bgOverlay: "linear-gradient(rgba(26,20,16,0.85), rgba(12,10,8,0.93))",
    catHeading: "text-3xl font-black uppercase tracking-widest text-amber-50 sm:text-4xl",
    catSub: "text-[11px] font-bold tracking-[0.4em] text-red-300",
    catRule: "border-amber-200/30",
    cardWrap: "flex gap-3 border-b-2 border-amber-200/20 bg-transparent px-1 py-3 sm:gap-4 sm:py-4",
    cardName: "text-sm font-bold uppercase tracking-wider text-amber-50 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-red-300 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-300 sm:text-xs",
    cardPrice: "text-sm font-black tabular-nums text-amber-200 sm:text-base",
    cardBadge: "rounded-sm bg-red-700 px-2 py-0.5 text-[10px] font-bold tracking-wider text-amber-50",
    cardImagePh: "bg-white/10 text-[10px] tracking-[0.2em] text-white/40",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-0 sm:grid-cols-2 sm:gap-x-10",
    footerNote: "text-amber-200/60",
    fontFamily: "font-sans",
    layout: "list",
  },
  family: {
    id: "family",
    pageBg: "bg-[#fffaf2]",
    pageText: "text-stone-900",
    headerBg: "bg-[#fffaf2]",
    headerText: "text-red-700",
    headerAccent: "text-orange-600",
    catHeading: "text-2xl font-bold text-stone-900 sm:text-3xl",
    catSub: "text-[11px] font-bold tracking-[0.3em] text-orange-600 uppercase",
    catRule: "border-orange-300",
    cardWrap: "flex gap-3 rounded-md border border-orange-200 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "text-sm font-semibold text-stone-900 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-orange-600 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-600 sm:text-xs",
    cardPrice: "text-sm font-bold tabular-nums text-red-700 sm:text-base",
    cardBadge: "rounded-sm bg-red-600 px-2 py-0.5 text-[10px] font-bold tracking-wider text-white",
    cardImagePh: "bg-orange-50 text-[10px] tracking-[0.2em] text-orange-300",
    sectionGap: "space-y-8 sm:space-y-10",
    grid: "grid gap-2 sm:grid-cols-2 sm:gap-3",
    footerNote: "text-stone-500",
    fontFamily: "font-sans",
    layout: "card",
  },
  bakery: {
    id: "bakery",
    pageBg: "bg-[#fbf6ee]",
    pageText: "text-amber-950",
    headerBg: "bg-[#fbf6ee]",
    headerText: "text-amber-950",
    headerAccent: "text-amber-700",
    catHeading:
      "font-serif text-2xl text-amber-950 sm:text-3xl",
    catSub: "text-[10px] tracking-[0.3em] text-amber-700 uppercase",
    catRule: "border-amber-200",
    cardWrap:
      "flex gap-3 rounded-md border border-amber-200 bg-white p-3 sm:gap-4 sm:p-4",
    cardName: "font-serif text-sm text-amber-950 sm:text-base",
    cardSub: "text-[10px] tracking-wider text-amber-700 sm:text-[11px]",
    cardDesc: "text-[11px] leading-relaxed text-stone-600 sm:text-xs",
    cardPrice: "font-serif text-sm text-amber-950 sm:text-base",
    cardBadge:
      "rounded-sm bg-amber-100 px-2 py-0.5 text-[10px] tracking-wider text-amber-800",
    cardImagePh: "bg-amber-50 text-[10px] tracking-[0.2em] text-amber-300",
    sectionGap: "space-y-10 sm:space-y-14",
    grid: "grid gap-3 sm:grid-cols-2 sm:gap-4",
    footerNote: "text-stone-500",
    fontFamily: "font-serif",
    layout: "card",
  },
};
